Update build_busybox_initramfs.yml

diff --git a/.github/workflows/build_busybox_initramfs.yml b/.github/workflows/build_busybox_initramfs.yml
--- a/.github/workflows/build_busybox_initramfs.yml
+++ b/.github/workflows/build_busybox_initramfs.yml
@@ -14,8 +14,7 @@ jobs:
       OUTPUT_DIR: ${{ github.workspace }}/output
 
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v3
+    - uses: actions/checkout@v3
 
     - name: Install dependencies
       run: |
@@ -37,54 +36,41 @@ jobs:
         wget -O busybox https://raw.githubusercontent.com/shutingrz/busybox-static-binaries-fat/main/busybox-aarch64-linux-gnu
         chmod +x busybox
         ln -sf busybox sh
-        file busybox
 
-    - name: Add init script
+    - name: Create init script
       run: |
-        cat > $INITRAMFS_DIR/init << 'EOF'
-#!/bin/sh
-
-echo "Booting BusyBox initramfs..."
-
-mount -t proc none /proc
-mount -t sysfs none /sys
-mount -t devtmpfs none /dev
-
-mkdir /newroot
-
-echo "Mounting Alpine rootfs image..."
-
-mount -t ext4 /dev/vda /newroot
-
-if [ $? -ne 0 ]; then
-    echo "Mount failed!"
-    exec sh
-fi
-
-mount --move /proc /newroot/proc
-mount --move /sys /newroot/sys
-mount --move /dev /newroot/dev
-
-echo "Switching to Alpine..."
-
-exec switch_root /newroot /sbin/init
-EOF
+        printf '%s\n' \
+        '#!/bin/sh' \
+        '' \
+        'echo "Booting BusyBox initramfs..."' \
+        'mount -t proc none /proc' \
+        'mount -t sysfs none /sys' \
+        'mount -t devtmpfs none /dev' \
+        '' \
+        'mkdir /newroot' \
+        'echo "Mounting Alpine rootfs image..."' \
+        'mount -t ext4 /dev/vda /newroot' \
+        '' \
+        'if [ $? -ne 0 ]; then' \
+        '  echo "Mount failed!"' \
+        '  exec sh' \
+        'fi' \
+        '' \
+        'mount --move /proc /newroot/proc' \
+        'mount --move /sys /newroot/sys' \
+        'mount --move /dev /newroot/dev' \
+        '' \
+        'exec switch_root /newroot /sbin/init' \
+        > $INITRAMFS_DIR/init
 
         chmod +x $INITRAMFS_DIR/init
 
-    - name: Build initramfs.cpio.gz
+    - name: Build initramfs
       run: |
         cd $INITRAMFS_DIR
         find . | cpio -o -H newc | gzip > $OUTPUT_DIR/initramfs.cpio.gz
 
-    - name: Verify initramfs
-      run: |
-        gzip -d -c $OUTPUT_DIR/initramfs.cpio.gz | cpio -t | grep -E "init|busybox|sh"
-
-    - name: Show output
-      run: ls -lh $OUTPUT_DIR
-
-    - name: Upload initramfs artifact
+    - name: Upload artifact
       uses: actions/upload-artifact@v4
       with:
         name: initramfs-arm64
